
modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="MIT"
[[mods]]
modId="shaman_king"
version="${mod_version}"
displayName="Shaman King"
authors="Shin" #optional

description='''Mod based on the series "Shaman King"'''
[[dependencies.shaman_king]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies.shaman_king]]
modId="geckolib"
mandatory=true
versionRange="[4.2,)"
ordering="NONE"
side="BOTH"
[[dependencies.shaman_king]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
